language: php

php:
  - 5.3
  - 5.4

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq git-flow

before_script:
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install
  - git config --global user.email "test@test.com"
  - git config --global user.name "John Doe"

script: phpunit

notifications:
  email:
    - bonndan76@googlemail.com

